package com.sgs.middle.eventControlModel;


public enum EventEnum {
    EVENT_TEST_MSG1,    //消息1
    EVENT_TEST_MSG2,    //消息2
    EVENT_TEST_SETMUSIC,    //消息2
    EVENT_TEST_SETCUTMSG,    //消息2
    EVENT_TEST_SETCLEARCUTMSG,    //消息2
    EVENT_TEST_DELETECUTMSG, //消息2
    EVENT_TEST_MSG2_KEY,//key
    EVENT_TEST_MSG2_KEY_MUSIC,//key
    EVENT_TEST_MSG2_KEY_ISPLAY_MUSIC,//key
    EVENT_TEST_MSG2_KEY_HTML_PATH,//key
    EVENT_TEST_MSG1_KEY_DELETECUTMSG,   //消息1
    EVENT_TEST_MSG1_KEY_CUTMSG;   //消息1
}
